const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../../openai-apikey.env') });
require('dotenv').config({ path: path.resolve(__dirname, '../../atlas-credentials.env') });

const mongoose = require('mongoose');
const Review = require('../server/models/Review');

const seedReviews = [
  {
    id: 'seed-01',
    date: '2026-07-12',
    time: '20:15',
    distillery: 'Lagavulin',
    whiskyName: 'Lagavulin 16',
    year: '16',
    abv: '43',
    type: 'Single Malt',
    region: 'Islay',
    nose: 'Humo intenso, sal marina y mantequilla tostada.',
    palate: 'Perejil, clavo, frutas oscuras y un toque de miel.',
    finish: 'Largo, ahumado y ligeramente cítrico.',
    overall: 'Una cata muy marcada, potente y muy clásica.',
    score: 91,
    price: '68 €',
    place: 'Madrid',
    transcript: 'Cata de Lagavulin 16 con nariz ahumada y final largo.',
    tags: ['ahumado', 'clásico', 'islay'],
    latitude: 40.4168,
    longitude: -3.7038,
    createdAt: new Date('2026-07-12T20:15:00Z'),
    updatedAt: new Date('2026-07-12T20:15:00Z')
  },
  {
    id: 'seed-02',
    date: '2026-07-14',
    time: '19:30',
    distillery: 'Glenmorangie',
    whiskyName: 'Glenmorangie Lasanta',
    year: '12',
    abv: '46',
    type: 'Single Malt',
    region: 'Highlands',
    nose: 'Naranja madura, miel y un toque de madera.',
    palate: 'Dulzor elegante con especias suaves y fruta seca.',
    finish: 'Media, limpia y con un final de vainilla.',
    overall: 'Muy accesible y agradable para una cata tranquila.',
    score: 84,
    price: '52 €',
    place: 'Barcelona',
    transcript: 'Glenmorangie Lasanta con notas de naranja y miel.',
    tags: ['dulce', 'afrutado', 'highlands'],
    latitude: 41.3851,
    longitude: 2.1734,
    createdAt: new Date('2026-07-14T19:30:00Z'),
    updatedAt: new Date('2026-07-14T19:30:00Z')
  },
  {
    id: 'seed-03',
    date: '2026-07-15',
    time: '21:00',
    distillery: 'Ardbeg',
    whiskyName: 'Ardbeg Uigeadail',
    year: '10',
    abv: '54.2',
    type: 'Single Malt',
    region: 'Islay',
    nose: 'Café, humo y ligero sabor a sal.',
    palate: 'Grasiento, especiado y con notas de cacao.',
    finish: 'Muy persistente y con mucha profundidad.',
    overall: 'Una cata potente y muy memorable.',
    score: 89,
    price: '74 €',
    place: 'Valencia',
    transcript: 'Ardbeg Uigeadail, muy potente y con final largo.',
    tags: ['humo', 'cacao', 'islay'],
    latitude: 39.4699,
    longitude: -0.3774,
    createdAt: new Date('2026-07-15T21:00:00Z'),
    updatedAt: new Date('2026-07-15T21:00:00Z')
  },
  {
    id: 'seed-04',
    date: '2026-07-17',
    time: '18:45',
    distillery: 'Talisker',
    whiskyName: 'Talisker Storm',
    year: '10',
    abv: '45.8',
    type: 'Single Malt',
    region: 'Islands',
    nose: 'Pimienta negra y sal marina.',
    palate: 'Picante, cítrico y con un fondo de melaza.',
    finish: 'Largo y especiado.',
    overall: 'Ideal para quienes gustan del carácter marcado.',
    score: 87,
    price: '59 €',
    place: 'Sevilla',
    transcript: 'Talisker Storm con un perfil picante y muy mineral.',
    tags: ['picante', 'isla', 'marino'],
    latitude: 37.3891,
    longitude: -5.9845,
    createdAt: new Date('2026-07-17T18:45:00Z'),
    updatedAt: new Date('2026-07-17T18:45:00Z')
  },
  {
    id: 'seed-05',
    date: '2026-07-19',
    time: '20:30',
    distillery: 'The Glenlivet',
    whiskyName: 'The Glenlivet 12',
    year: '12',
    abv: '40',
    type: 'Single Malt',
    region: 'Speyside',
    nose: 'Manzana, pera y flores blancas.',
    palate: 'Suave, equilibrado y con un toque de miel.',
    finish: 'Corta pero elegante.',
    overall: 'Muy bien para introducirse en un Speyside clásico.',
    score: 82,
    price: '44 €',
    place: 'Bilbao',
    transcript: 'The Glenlivet 12 con notas afrutadas y suave.',
    tags: ['afrutado', 'equilibrado', 'speyside'],
    latitude: 43.2630,
    longitude: -2.9350,
    createdAt: new Date('2026-07-19T20:30:00Z'),
    updatedAt: new Date('2026-07-19T20:30:00Z')
  },
  {
    id: 'seed-06',
    date: '2026-07-21',
    time: '22:00',
    distillery: 'Bowmore',
    whiskyName: 'Bowmore 12',
    year: '12',
    abv: '40',
    type: 'Single Malt',
    region: 'Islay',
    nose: 'Humo suave, algas y fruta de hueso.',
    palate: 'Madera, sal y una nota de tomate seco.',
    finish: 'Media, con profundidad y madera.',
    overall: 'Una cata muy elegante y con personalidad.',
    score: 86,
    price: '57 €',
    place: 'Málaga',
    transcript: 'Bowmore 12 con humo cuidado y notas marinas.',
    tags: ['marino', 'elegante', 'islay'],
    latitude: 36.7213,
    longitude: -4.4213,
    createdAt: new Date('2026-07-21T22:00:00Z'),
    updatedAt: new Date('2026-07-21T22:00:00Z')
  },
  {
    id: 'seed-07',
    date: '2026-07-23',
    time: '19:15',
    distillery: 'Macallan',
    whiskyName: 'Macallan 12',
    year: '12',
    abv: '40',
    type: 'Single Malt',
    region: 'Highlands',
    nose: 'Vainilla, fruta madura y caramelo.',
    palate: 'Suave, cremoso y con toffee.',
    finish: 'Larga y muy amable.',
    overall: 'Muy redondo y fácil de disfrutar.',
    score: 88,
    price: '66 €',
    place: 'Zaragoza',
    transcript: 'Macallan 12 muy cremoso y con perfil dulce.',
    tags: ['cremoso', 'vainilla', 'highlands'],
    latitude: 41.6488,
    longitude: -0.8891,
    createdAt: new Date('2026-07-23T19:15:00Z'),
    updatedAt: new Date('2026-07-23T19:15:00Z')
  },
  {
    id: 'seed-08',
    date: '2026-07-24',
    time: '20:45',
    distillery: 'Springbank',
    whiskyName: 'Springbank 10',
    year: '10',
    abv: '46',
    type: 'Single Malt',
    region: 'Campbeltown',
    nose: 'Fruta cítrica, sal y aceite.',
    palate: 'Peculiar, con un toque de tierra y especias.',
    finish: 'Muy marcada y persistente.',
    overall: 'Una cata muy diferente, muy interesante.',
    score: 85,
    price: '63 €',
    place: 'Pamplona',
    transcript: 'Springbank 10 con personalidad muy marcada y salina.',
    tags: ['salino', 'campbeltown', 'diferente'],
    latitude: 42.8125,
    longitude: -1.6458,
    createdAt: new Date('2026-07-24T20:45:00Z'),
    updatedAt: new Date('2026-07-24T20:45:00Z')
  },
  {
    id: 'seed-09',
    date: '2026-07-26',
    time: '18:20',
    distillery: 'Highland Park',
    whiskyName: 'Highland Park 12',
    year: '12',
    abv: '40',
    type: 'Single Malt',
    region: 'Islands',
    nose: 'Miel, nuez y una ligera nota de turba.',
    palate: 'Sutilmente especiado y con fruta roja.',
    finish: 'Ligeramente ahumado y muy limpio.',
    overall: 'Muy elegante y bien redondeado.',
    score: 83,
    price: '49 €',
    place: 'Santander',
    transcript: 'Highland Park 12 con notas de nuez y fruta roja.',
    tags: ['nuez', 'elegante', 'islands'],
    latitude: 43.4623,
    longitude: -3.8099,
    createdAt: new Date('2026-07-26T18:20:00Z'),
    updatedAt: new Date('2026-07-26T18:20:00Z')
  },
  {
    id: 'seed-10',
    date: '2026-07-28',
    time: '21:30',
    distillery: 'Laphroaig',
    whiskyName: 'Laphroaig 10',
    year: '10',
    abv: '48',
    type: 'Single Malt',
    region: 'Islay',
    nose: 'Humo intenso, sal y yodo.',
    palate: 'Muy medicinal y con un fondo de madera.',
    finish: 'Largo, potente y muy marcado.',
    overall: 'Muy intenso, ideal para amantes del humo.',
    score: 90,
    price: '61 €',
    place: 'A Coruña',
    transcript: 'Laphroaig 10 con humo intenso y perfil medicinal.',
    tags: ['humo', 'medicinal', 'islay'],
    latitude: 43.3623,
    longitude: -8.4115,
    createdAt: new Date('2026-07-28T21:30:00Z'),
    updatedAt: new Date('2026-07-28T21:30:00Z')
  },
  {
    id: 'seed-11',
    date: '2026-07-30',
    time: '19:45',
    distillery: 'Glenfiddich',
    whiskyName: 'Glenfiddich 15',
    year: '15',
    abv: '40',
    type: 'Single Malt',
    region: 'Speyside',
    nose: 'Manzana, miel y un toque de flor.',
    palate: 'Suave y afrutado, con vainilla.',
    finish: 'Limpia y agradable.',
    overall: 'Gran opción para una cata relajada.',
    score: 81,
    price: '39 €',
    place: 'Vigo',
    transcript: 'Glenfiddich 15 con notas de manzana y miel.',
    tags: ['frutal', 'suave', 'speyside'],
    latitude: 42.2406,
    longitude: -8.7207,
    createdAt: new Date('2026-07-30T19:45:00Z'),
    updatedAt: new Date('2026-07-30T19:45:00Z')
  },
  {
    id: 'seed-12',
    date: '2026-08-01',
    time: '20:00',
    distillery: 'Bruichladdich',
    whiskyName: 'Bruichladdich Classic Laddie',
    year: '10',
    abv: '46',
    type: 'Single Malt',
    region: 'Islay',
    nose: 'Cítricos, flor y ligera sal.',
    palate: 'Acidez fresca, miel y frutos secos.',
    finish: 'Larga y brillante.',
    overall: 'Muy equilibrado y sorprendentemente fresco.',
    score: 85,
    price: '54 €',
    place: 'Granada',
    transcript: 'Classic Laddie con perfil fresco y cítrico.',
    tags: ['cítrico', 'fresco', 'islay'],
    latitude: 37.1882,
    longitude: -3.6067,
    createdAt: new Date('2026-08-01T20:00:00Z'),
    updatedAt: new Date('2026-08-01T20:00:00Z')
  },
  {
    id: 'seed-13',
    date: '2026-08-02',
    time: '21:15',
    distillery: 'Bunnahabhain',
    whiskyName: 'Bunnahabhain 12',
    year: '12',
    abv: '46.3',
    type: 'Single Malt',
    region: 'Islay',
    nose: 'Miel, manzana y una leve sal.',
    palate: 'Muy suave, con lácteos y algo de madera.',
    finish: 'Media y equilibrada.',
    overall: 'Ideal para quienes quieren algo menos agresivo.',
    score: 84,
    price: '48 €',
    place: 'Toledo',
    transcript: 'Bunnahabhain 12 suave, afrutado y equilibrado.',
    tags: ['suave', 'equilibrado', 'islay'],
    latitude: 39.8628,
    longitude: -4.0273,
    createdAt: new Date('2026-08-02T21:15:00Z'),
    updatedAt: new Date('2026-08-02T21:15:00Z')
  },
  {
    id: 'seed-14',
    date: '2026-08-03',
    time: '19:00',
    distillery: 'Royal Lochnagar',
    whiskyName: 'Royal Lochnagar 12',
    year: '12',
    abv: '40',
    type: 'Single Malt',
    region: 'Highlands',
    nose: 'Fruta blanca, flores y ligera madera.',
    palate: 'Muy delicado, con un toque de miel.',
    finish: 'Corta pero muy limpia.',
    overall: 'Una cata muy refinada y fácil.',
    score: 80,
    price: '45 €',
    place: 'Murcia',
    transcript: 'Royal Lochnagar 12 delicado y muy refinado.',
    tags: ['delicado', 'refinado', 'highlands'],
    latitude: 37.9922,
    longitude: -1.1307,
    createdAt: new Date('2026-08-03T19:00:00Z'),
    updatedAt: new Date('2026-08-03T19:00:00Z')
  },
  {
    id: 'seed-15',
    date: '2026-08-04',
    time: '20:15',
    distillery: 'Octomore',
    whiskyName: 'Octomore 8.3',
    year: '8',
    abv: '59.1',
    type: 'Single Malt',
    region: 'Islay',
    nose: 'Turba intensa, sal y madera quemada.',
    palate: 'Muy potente, con café tostado y especias.',
    finish: 'Excepcionalmente larga y agresiva.',
    overall: 'Una cata extrema para paladares muy definidos.',
    score: 94,
    price: '92 €',
    place: 'Las Palmas',
    transcript: 'Octomore 8.3 muy potente y con turba intensa.',
    tags: ['turba', 'extremo', 'islay'],
    latitude: 28.1235,
    longitude: -15.4363,
    createdAt: new Date('2026-08-04T20:15:00Z'),
    updatedAt: new Date('2026-08-04T20:15:00Z')
  }
];

async function seed() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    throw new Error('Missing MONGODB_URI');
  }

  await mongoose.connect(uri);
  console.log('Connected to MongoDB Atlas');

  await Review.deleteMany({});
  const inserted = await Review.insertMany(seedReviews);
  console.log(`Seeded ${inserted.length} reviews`);

  await mongoose.disconnect();
  console.log('Seed completed');
}

seed().catch((err) => {
  console.error('Seed error:', err.message);
  process.exit(1);
});
